# Generated by Django 4.2.1 on 2023-06-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayApp', '0002_producto_totalproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='totalProducto',
            field=models.CharField(max_length=50),
        ),
    ]
