# Generated by Django 4.1.2 on 2023-06-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bayApp', '0004_alter_producto_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descriptionModel',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='img',
            new_name='imgModel',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='nameModel',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='priceModel',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='totalProducto',
            new_name='totalProductModel',
        ),
    ]
